export default {
    h1: '//h1',
    mainMenuBar: '//div[@class="nb2018-navigation-wrap"]//div[@aria-label="Navigation Menu"]',
    logoHeader: '//div[@class="nb2018-logo-wrap logo-white"]//img[@class="nb2018-logo"]',
    platformMenuElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Platform")]',
    documentWorkflow: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Document Workflow")]',
    careCoordination: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Care Coordination")]',
    forYourRoleMenuElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"For Your Role")]',
    executive: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Executive")]',
    technical: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Technical")]',
    administrator: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Administrator")]',
    blogElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Blog")]',
    resourcesElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Resources")]',
    companyElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Company")]',
    aboutUs: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"About Us")]',
    customers: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Customers")]',
    partners: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Partners")]',
    newsroom: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Newsroom")]',
    careers: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Careers")]',
    innovateJax: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Innovate Jax")]',
    loginElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Login")]',
    scheduleDemoButton: '//div[@class="nb2018-navigation-wrap"]//a[@title="Schedule Demo"]',
    footerBottom: '//div[@class="nb2018-footer-bottom"]',
    subscribeToBlogButton: '//form[@id="hsForm_09126227-199b-4ede-870e-28dfebd04250"]//input[@class="hs-button primary large"]',
    submittedSubsription: '//div[@class="submitted-message hs-main-font-element hs-form-09126227-199b-4ede-870e-28dfebd04250 hs-form-09126227-199b-4ede-870e-28dfebd04250_bc6e019d-011f-4e28-9d33-62ab6b57a604"]',
    subscribeEmailField: '//input[@id="email-09126227-199b-4ede-870e-28dfebd04250"]',
    subscribeMessage: '//label[@class="hs-main-font-element"]'

}