export default {
    h1: '//h1',
    mainMenuBar: '//div[@class="nb2018-navigation-wrap"]//div[@aria-label="Navigation Menu"]',
    logoHeader: '//div[@class="nb2018-logo-wrap logo-white"]//img[@class="nb2018-logo"]',
    platformMenuElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Platform")]',
    documentWorkflow: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Document Workflow")]',
    careCoordination: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Care Coordination")]',
    forYourRoleMenuElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"For Your Role")]',
    executive: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Executive")]',
    technical: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Technical")]',
    administrator: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Administrator")]',
    blogElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Blog")]',
    resourcesElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Resources")]',
    companyElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Company")]',
    aboutUs: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"About Us")]',
    customers: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Customers")]',
    partners: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Partners")]',
    newsroom: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Newsroom")]',
    careers: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Careers")]',
    innovateJax: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Innovate Jax")]',
    loginElement: '//div[@class="nb2018-navigation-wrap"]//a[contains(text(),"Login")]',
    scheduleDemoButton: '//div[@class="nb2018-navigation-wrap"]//a[@title="Schedule Demo"]',
    footerBottom: '//div[@class="nb2018-footer-bottom"]',
    subscribeToBlogButton: '//input[@class="hs-button primary large"]',
    submittedSubscription: '//div[@data-reactid=".hbspt-forms-0"]',
    subscribeEmailField: '//input[@id="email-09126227-199b-4ede-870e-28dfebd04250"]',
    subscribeMessage: '//label[@class="hs-main-font-element"]',
    iframe: '//*[@id="hubspot-messages-iframe-container"]/iframe',
    iframeInitialMessage: '//div[@class="initial-message-bubble"]//p[contains(text(), "Got any questions? I\'m happy to help.")]',
    iframeOpenChatButton: '//button[@aria-label="Open live chat"]',
    iframeCloseChatButton: '//button[@aria-label="Close live chat"]',
    iframeChat: '//div[@class="VisitorWidgetStyleWrapper__WidgetStyleWrapper-hGFLTF iSMkkU"]',
    primaryChatMessage: '//div[@class="ContentText__ContentTextWrapper-fUdYiW hnNGBv"]/div[contains(text(), "Got any questions? I\'m happy to help.")]',
    secondaryChatMessage: '//div[@class="ContentText__ContentTextWrapper-fUdYiW hnNGBv"]//div[contains(text(), "Do you have a sales inquiry or need product support?")]',
    salesInquiryButton: '//span[contains(text(), "Sales Inquiry")]',
    productSupportButton: '//span[contains(text(), "Product Support")]',
    inquirySalesAnswer: '//div[contains(text(), "Okay. What question do you have?")]',
    productSupportAnswer1: '//div[contains(text(), "To submit a support request please email ")]',
    productSupportAnswer2: '//div[contains(text(), "A support representative will then reach out to you shortly.")]',
    productSupportAnswer3: '//div[contains(text(), "Thank you.")]',
    iframeChatPlaceholder: '//textarea[@placeholder="Write a message"]',
    iframeUiIconLeft: '//span[@data-icon-name="left"]',
    iframeUiIconRight: '//span[@data-icon-name="description"]'



}